### ISSUE TITLE
[Feat] Reminder Project 초기 설정

### ISSUE THREAD

**Issue by alpaka99** [alpaka99/Reminder-Project#1]
### 작업 설명 🛠️
프로젝트의 초기 설정을 진행합니다
- CodeBased UIKit Project 설정을 진행합니다
- 프로젝트에 필요한 SnapKit, Realm 라이브러리의 의존성을 추가합니다.
- 추가적인 info.plist 수정을 진행합니다
- .gitIgnore 파일을 생성 및 추가합니다

### Todos ✅

- [x] Main.storyboard 삭제 및 설정
- [x] SceneDelegate 설정
- [x] SnapKit, Realm 의존성 추가
- [x] .gitIgnore 파일 추가
