### ISSUE TITLE
[Feat]

### ISSUE THREAD

**Issue by alpaka99** [alpaka99/Reminder-Project#17]
### 작업 설명 🛠️
- RegisterView의 StackView를 TableView로 변경하기

### Todos ✅
- [ ] TableView의 Footer를 수정하는 방법으로 TableView에서의 불필요한 spacing을 제거합니다
- [ ] (option) Disclosure 버튼이 뷰를 열고 접을 수 있게 하는 기능을 만듭니다
- [ ] (option) DisclosureCell을 열고 닫을 수 있는 방법을 생각해봅니다
