### ISSUE TITLE
[Feat] 등록 화면 추가 기능 구현

### ISSUE THREAD

**Issue by alpaka99** [alpaka99/Reminder-Project#20]
### 작업 설명 🛠️
- 등록 화면의 추가 기능을 구현합니다

### Todos ✅
- [x] 마감일, 태그, 우선순위, 이미지 추가를 누르면 뷰 컨트롤러가 push됩니다
- [x] 마감일 화면은 DatePicker가 있고, 뒤로가기를 누르면 설정한 날짜가 등록 화면에 반영됩니다
- [x] 태그 화면은 textField가 하나 있고, 뒤로가기를 누르면 작성한 문자열이 등록 화면에 반영됩니다
- [x] 우선 순위 화면은 SegmentedControl 하나만 있고, 뒤로가기를 누르면 세그먼트 컨트롤에서 선택한 값이 등록 화면에 반영됩니다.
- [x] 이미지 추가 버튼을 누르면 갤러리가 보여지고, 선택한 이미지가 셀 우측에 보여집니다
