### ISSUE TITLE
[Feat] 세가지 화면의 layout 및 UI를 구현합니다

### ISSUE THREAD

**Issue by alpaka99** [alpaka99/Reminder-Project#5]
### 작업 설명 🛠️
- 메인 화면, 등록 화면, 목록 화면에 대한 Layout 및 UI를 구현합니다.

### Todos ✅

- [x] 메인 화면 Layout 및 UI 작성
- [x] 등록 화면 Layout 및 UI 작성
- [x] 목록 화면 Layout 및 UI 작성

|관련|이미지|
|--|--|
|메인 화면|<img width="170" alt="image" src="https://github.com/alpaka99/Reminder-Project/assets/22471820/9d2e73ad-b50b-482d-87c2-6f1157ec58ac">|
|등록 화면|<img width="153" alt="image" src="https://github.com/alpaka99/Reminder-Project/assets/22471820/3497028c-5bee-41c5-be5e-5ac5811b5c59">|
|목록 화면|<img width="166" alt="image" src="https://github.com/alpaka99/Reminder-Project/assets/22471820/877e2434-86f6-4731-b67c-e1c51e0eed96">|
