### ISSUE TITLE
[Feat] Realm을 이용한 DB를 구축합니다

### ISSUE THREAD

**Issue by alpaka99** [alpaka99/Reminder-Project#7]
### 작업 설명 🛠️
- Realm을 이용해서 Local DB를 구축합니다. 데이터 테이블을 어떻게 구축할지 생각해보고, CRUD에 해당하는 동작들을 해봅니다.

### Todos ✅
- [x] Realm을 이용해서 Local DB를 구축합니다
- [x] 등록 화면에서 Create를 진행해봅니다
- [x] 목록 화면에서 Read, Delete를 진행해봅니다
