### ISSUE TITLE
[Feat] Navigation을 연결합니다

### ISSUE THREAD

**Issue by alpaka99** [alpaka99/Reminder-Project#8]
### 작업 설명 🛠️
현재 분리되어있는 뷰들의 Navigation을 연결합니다

### Todos ✅
- [x] Scenedelegate 설정을 통해 mainview를 가장 처음에 보여줍니다
- [x] navigation을 통해 적절한 뷰들로 이동할 수 있도록 합니다
- [x] viewController에 알맞은 navigation 버튼들을 달 수 있도록 합니다
